version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: deploy
      MYSQL_PASSWORD: deploy1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge

